import localFont from "next/font/local";
import "./globals.css";
import NavWrapper from "./Shared/NavWrapper";
import Footer from "./Shared/Footer";
import { Kanit, Open_Sans, Poppins } from "next/font/google";
const fontName = Kanit({ subsets: ["latin"], weight: "400" });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata = {
  title: "HijiBusy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="light" lang="en">
      <body className={`${fontName.className} antialiased my-2`}>
        <NavWrapper /> {children} <Footer />
      </body>
    </html>
  );
}
