// import localFont from "next/font/local";
// import "./globals.css";
// import NavWrapper from "./Shared/NavWrapper";
// import { Kanit, Open_Sans, Poppins } from "next/font/google";
// import FooterWrapper from "./Shared/FooterWrapper";
// import Loader from "./loader";
// import GoogleTranslate from "@/components/GoogleTranslate";
// const fontName = Kanit({ subsets: ["latin"], weight: "400" });
// // const geistMono = localFont({
// //   src: "./fonts/GeistMonoVF.woff",
// //   variable: "--font-geist-mono",
// //   weight: "100 900",
// // });

// export const metadata = {
//   title: "HijiBusy",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html data-theme="light" lang="en">
//       <body
//         data-theme="light"
//         className={`${fontName.className} antialiased my-2`}
//       >
//         <NavWrapper />
//         {/* Google Translate Component (Client-Side) */}
//         <GoogleTranslate />
//         <Loader> {children} </Loader> <FooterWrapper />
//       </body>
//     </html>
//   );
// }

import "./globals.css";
import NavWrapper from "./Shared/NavWrapper";
import { Kanit } from "next/font/google";
import FooterWrapper from "./Shared/FooterWrapper";
import Loader from "./loader";
import dynamic from "next/dynamic";

// ✅ Load GoogleTranslate dynamically to avoid hydration issues
const GoogleTranslate = dynamic(() => import("@/components/GoogleTranslate"), {
  ssr: false,
});

const fontName = Kanit({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "HijiBusy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="light" lang="en">
      <body
        data-theme="light"
        className={`${fontName.className} antialiased my-2`}
      >
        <NavWrapper />

        {/* ✅ Ensures Google Translate is loaded only once */}
        <GoogleTranslate />

        <Loader>{children}</Loader>
        <FooterWrapper />
      </body>
    </html>
  );
}
